packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  turbo: ^2.8.16
  typescript: ~5.9.3
  eslint: ^9.39.4
  prettier: ^3.8.1
  '@eslint/js': ^9.0.0
  typescript-eslint: ^8.57.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-turbo: ^2.8.16
  zod: ^4.0.0
  '@t3-oss/env-core': ^0.13.10
  tsup: ^8.5.1
  drizzle-orm: ^0.45.1
  better-sqlite3: ^12.6.2
  drizzle-kit: ^0.31.9
  '@types/better-sqlite3': ^7.6.13
  hono: ^4.12.7
  '@hono/node-server': ^1.19.11
  '@hono/zod-validator': ^0.7.6
  tsx: ^4.21.0
